Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/focal64"

  config.vm.define "APP_VM" do |app|
    app.vm.hostname = "app-vm"

    # Проброс порту 8080 з гостьової ВМ на хост
    app.vm.network "forwarded_port", guest: 8080, host: 8080


    app.vm.provision "shell", path: "provision/app_provision.sh",
      env: {
        "DB_HOST" => "10.0.2.15",
        "DB_PORT" => "3306",
        "DB_NAME" => ENV["DB_NAME"],
        "DB_USER" => ENV["DB_USER"],
        "DB_PASS" => ENV["DB_PASS"],
        "APP_USER" => ENV["APP_USER"] || "appuser",
        "PROJECT_DIR" => ENV["PROJECT_DIR"] || "/home/appuser/project",
        "APP_DIR" => ENV["APP_DIR"] || "/home/appuser/app"
      }

    app.vm.provider "virtualbox" do |vb|
      vb.name = "APP_VM"
      vb.memory = 1024
      vb.cpus = 1
    end
  end

  config.vm.define "DB_VM" do |db|
    db.vm.hostname = "db-vm"

    db.vm.network "private_network", ip: "192.168.56.11"
    db.vm.provision "shell",
      path: "C:/Users/admin/provision/db_provision.sh",
      env: {
        "DB_USER" => ENV["DB_USER"],
        "DB_PASS" => ENV["DB_PASS"],
        "DB_NAME" => ENV["DB_NAME"]
      }
    db.vm.provider "virtualbox" do |vb|
      vb.name = "DB_VM"
      vb.memory = 1024
      vb.cpus = 1
    end
  end
end
